/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125AboutRouteImport } from './routes/{-$lang}/about'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125PricingRouteImport } from './routes/{-$lang}/pricing'
import { Route as Char123LangChar125ProcessRouteImport } from './routes/{-$lang}/process'
import { Route as Char123LangChar125ServicesRouteImport } from './routes/{-$lang}/services'
import { Route as AdminInvoicePrintIdRouteImport } from './routes/admin/invoice-print.$id'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices.index'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin/invoices.$id'
import { Route as AdminLetterPrintIdRouteImport } from './routes/admin/letter-print.$id'
import { Route as AdminLettersIndexRouteImport } from './routes/admin/letters.index'
import { Route as AdminLettersIdRouteImport } from './routes/admin/letters.$id'
import { Route as Char123LangChar125WorkIndexRouteImport } from './routes/{-$lang}/work.index'
import { Route as Char123LangChar125WorkSlugRouteImport } from './routes/{-$lang}/work.$slug'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125AboutRoute = Char123LangChar125AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125PricingRoute =
  Char123LangChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ProcessRoute =
  Char123LangChar125ProcessRouteImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ServicesRoute =
  Char123LangChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const AdminInvoicePrintIdRoute = AdminInvoicePrintIdRouteImport.update({
  id: '/invoice-print/$id',
  path: '/invoice-print/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLetterPrintIdRoute = AdminLetterPrintIdRouteImport.update({
  id: '/letter-print/$id',
  path: '/letter-print/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLettersIndexRoute = AdminLettersIndexRouteImport.update({
  id: '/letters/',
  path: '/letters/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLettersIdRoute = AdminLettersIdRouteImport.update({
  id: '/letters/$id',
  path: '/letters/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char123LangChar125WorkIndexRoute =
  Char123LangChar125WorkIndexRouteImport.update({
    id: '/work/',
    path: '/work/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125WorkSlugRoute =
  Char123LangChar125WorkSlugRouteImport.update({
    id: '/work/$slug',
    path: '/work/$slug',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/process': typeof Char123LangChar125ProcessRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/admin/invoice-print/$id': typeof AdminInvoicePrintIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/letter-print/$id': typeof AdminLetterPrintIdRoute
  '/admin/letters/$id': typeof AdminLettersIdRoute
  '/{-$lang}/work/$slug': typeof Char123LangChar125WorkSlugRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/letters/': typeof AdminLettersIndexRoute
  '/{-$lang}/work/': typeof Char123LangChar125WorkIndexRoute
}
export interface FileRoutesByTo {
  '/admin/clients': typeof AdminClientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/process': typeof Char123LangChar125ProcessRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/admin': typeof AdminIndexRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/admin/invoice-print/$id': typeof AdminInvoicePrintIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/letter-print/$id': typeof AdminLetterPrintIdRoute
  '/admin/letters/$id': typeof AdminLettersIdRoute
  '/{-$lang}/work/$slug': typeof Char123LangChar125WorkSlugRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/letters': typeof AdminLettersIndexRoute
  '/{-$lang}/work': typeof Char123LangChar125WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/process': typeof Char123LangChar125ProcessRoute
  '/{-$lang}/services': typeof Char123LangChar125ServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/admin/invoice-print/$id': typeof AdminInvoicePrintIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/letter-print/$id': typeof AdminLetterPrintIdRoute
  '/admin/letters/$id': typeof AdminLettersIdRoute
  '/{-$lang}/work/$slug': typeof Char123LangChar125WorkSlugRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/letters/': typeof AdminLettersIndexRoute
  '/{-$lang}/work/': typeof Char123LangChar125WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/{-$lang}'
    | '/admin/clients'
    | '/admin/messages'
    | '/admin/settings'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/pricing'
    | '/{-$lang}/process'
    | '/{-$lang}/services'
    | '/admin/'
    | '/{-$lang}/'
    | '/admin/invoice-print/$id'
    | '/admin/invoices/$id'
    | '/admin/letter-print/$id'
    | '/admin/letters/$id'
    | '/{-$lang}/work/$slug'
    | '/admin/invoices/'
    | '/admin/letters/'
    | '/{-$lang}/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/clients'
    | '/admin/messages'
    | '/admin/settings'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/pricing'
    | '/{-$lang}/process'
    | '/{-$lang}/services'
    | '/admin'
    | '/{-$lang}'
    | '/admin/invoice-print/$id'
    | '/admin/invoices/$id'
    | '/admin/letter-print/$id'
    | '/admin/letters/$id'
    | '/{-$lang}/work/$slug'
    | '/admin/invoices'
    | '/admin/letters'
    | '/{-$lang}/work'
  id:
    | '__root__'
    | '/admin'
    | '/{-$lang}'
    | '/admin/clients'
    | '/admin/messages'
    | '/admin/settings'
    | '/{-$lang}/about'
    | '/{-$lang}/contact'
    | '/{-$lang}/pricing'
    | '/{-$lang}/process'
    | '/{-$lang}/services'
    | '/admin/'
    | '/{-$lang}/'
    | '/admin/invoice-print/$id'
    | '/admin/invoices/$id'
    | '/admin/letter-print/$id'
    | '/admin/letters/$id'
    | '/{-$lang}/work/$slug'
    | '/admin/invoices/'
    | '/admin/letters/'
    | '/{-$lang}/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/about': {
      id: '/{-$lang}/about'
      path: '/about'
      fullPath: '/{-$lang}/about'
      preLoaderRoute: typeof Char123LangChar125AboutRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/pricing': {
      id: '/{-$lang}/pricing'
      path: '/pricing'
      fullPath: '/{-$lang}/pricing'
      preLoaderRoute: typeof Char123LangChar125PricingRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/process': {
      id: '/{-$lang}/process'
      path: '/process'
      fullPath: '/{-$lang}/process'
      preLoaderRoute: typeof Char123LangChar125ProcessRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/services': {
      id: '/{-$lang}/services'
      path: '/services'
      fullPath: '/{-$lang}/services'
      preLoaderRoute: typeof Char123LangChar125ServicesRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/admin/invoice-print/$id': {
      id: '/admin/invoice-print/$id'
      path: '/invoice-print/$id'
      fullPath: '/admin/invoice-print/$id'
      preLoaderRoute: typeof AdminInvoicePrintIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/letter-print/$id': {
      id: '/admin/letter-print/$id'
      path: '/letter-print/$id'
      fullPath: '/admin/letter-print/$id'
      preLoaderRoute: typeof AdminLetterPrintIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/letters/': {
      id: '/admin/letters/'
      path: '/letters'
      fullPath: '/admin/letters/'
      preLoaderRoute: typeof AdminLettersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/letters/$id': {
      id: '/admin/letters/$id'
      path: '/letters/$id'
      fullPath: '/admin/letters/$id'
      preLoaderRoute: typeof AdminLettersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/{-$lang}/work/': {
      id: '/{-$lang}/work/'
      path: '/work'
      fullPath: '/{-$lang}/work/'
      preLoaderRoute: typeof Char123LangChar125WorkIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/work/$slug': {
      id: '/{-$lang}/work/$slug'
      path: '/work/$slug'
      fullPath: '/{-$lang}/work/$slug'
      preLoaderRoute: typeof Char123LangChar125WorkSlugRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInvoicePrintIdRoute: typeof AdminInvoicePrintIdRoute
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
  AdminLetterPrintIdRoute: typeof AdminLetterPrintIdRoute
  AdminLettersIdRoute: typeof AdminLettersIdRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminLettersIndexRoute: typeof AdminLettersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInvoicePrintIdRoute: AdminInvoicePrintIdRoute,
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
  AdminLetterPrintIdRoute: AdminLetterPrintIdRoute,
  AdminLettersIdRoute: AdminLettersIdRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminLettersIndexRoute: AdminLettersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125AboutRoute: typeof Char123LangChar125AboutRoute
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125PricingRoute: typeof Char123LangChar125PricingRoute
  Char123LangChar125ProcessRoute: typeof Char123LangChar125ProcessRoute
  Char123LangChar125ServicesRoute: typeof Char123LangChar125ServicesRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125WorkSlugRoute: typeof Char123LangChar125WorkSlugRoute
  Char123LangChar125WorkIndexRoute: typeof Char123LangChar125WorkIndexRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125AboutRoute: Char123LangChar125AboutRoute,
    Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
    Char123LangChar125PricingRoute: Char123LangChar125PricingRoute,
    Char123LangChar125ProcessRoute: Char123LangChar125ProcessRoute,
    Char123LangChar125ServicesRoute: Char123LangChar125ServicesRoute,
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
    Char123LangChar125WorkSlugRoute: Char123LangChar125WorkSlugRoute,
    Char123LangChar125WorkIndexRoute: Char123LangChar125WorkIndexRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
